# Generated by Django 4.0.3 on 2022-04-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_item_todolist_todolist_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='ToDo',
        ),
        migrations.AddField(
            model_name='todolist',
            name='ToDo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
