# Generated by Django 4.0.3 on 2022-04-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_todolist_todo_todolist_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='ToDo',
        ),
        migrations.AddField(
            model_name='item',
            name='todolist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.todolist'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='To Do List name'),
        ),
    ]
