# Generated by Django 4.0.3 on 2022-04-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_todolist_todo_item_todolist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='todolist',
        ),
        migrations.AddField(
            model_name='todolist',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
