# Generated by Django 4.0.3 on 2022-04-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_item_todolist_todolist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='todolist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.todolist'),
        ),
    ]
