# Generated by Django 4.0.3 on 2022-04-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_todolist_item_item_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstructionDetail', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='todolist',
            new_name='ToDoList',
        ),
        migrations.AddField(
            model_name='item',
            name='InstructionDetail',
            field=models.ManyToManyField(blank=True, to='main.instruction'),
        ),
    ]
