# Generated by Django 4.0.3 on 2022-04-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_todolist2_item2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item2',
            name='ToDoList2',
        ),
        migrations.AddField(
            model_name='item2',
            name='todolist2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='main.todolist2'),
        ),
    ]
